# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\Usuarios: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        our_db_provider:
            entity:
                class: AppBundle:Usuarios
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            provider: our_db_provider
            http_basic: ~
        admin:
            pattern: ^/evento
            provider: our_db_provider
            http_basic: ~
        main:
            anonymous: ~
            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: /
                check_path: /
            logout:
                path:   /logout
                target: /
            # activate different ways to authenticate
            pattern: ^/
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic: ~
            provider: our_db_provider

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/evento, roles: ROLE_USER }
